baseURL = "https://test-website123323.netlify.app/"
languageCode = "en-us"
title = "Test site"

# 기본 빌드 설정
publishDir = "public"
disableKinds = []  # 필요하지 않은 페이지 유형 비활성화

[build]
  writeStats = true

[params]
  description = "Your site description"
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2