baseURL = "https://test-website123323.netlify.app/"
languageCode = "en-us"
title = "Test Website"

# 메뉴 설정
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

[params]
  description = "A test website built with Hugo"