[build]
  publish = "public"
  command = "hugo -v --gc --minify"  # -v 플래그로 자세한 로그 활성화

[build.environment]
  HUGO_VERSION = "0.111.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy: 
  default-src 'self'; 
  script-src 'self' https://identity.netlify.com https://unpkg.com https://cdn.jsdelivr.net https://ajax.googleapis.com 'unsafe-inline' 'unsafe-eval'; 
  style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://use.fontawesome.com https://cdn.jsdelivr.net; 
  font-src 'self' https://fonts.gstatic.com https://use.fontawesome.com; 
  img-src 'self' data: blob: https://images.unsplash.com; 
  connect-src 'self' https://api.netlify.com https://identity.netlify.com;

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404