[build]
base = "mysite"
  command = "hugo --minify"
  publish = "public"


[build.environment]
HUGO_VERSION = "0.147.8"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "18"

[context.production.environment]
HUGO_ENV = "production"
